# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20180724_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['id'], 'permissions': (('view_server', 'can view server'), ('change_server_status', 'can change the status of server'))},
        ),
    ]
