# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='mail',
            field=models.CharField(help_text='联系邮件', max_length=32, null=True, verbose_name='联系邮件'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='remark',
            field=models.CharField(help_text='备注', max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='tel',
            field=models.CharField(help_text='联系电话', max_length=15, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='vendor_name',
            field=models.CharField(db_index=True, help_text='厂商名称', max_length=32, unique=True, verbose_name='厂商名称'),
        ),
    ]
